const CACHE_NAME="structureco-shell-e2f6043f28170342";
const SHELL=["./assets/CommandPalette-B0lZhPHH.js","./assets/DatasheetPanel-B6A7CNTV.js","./assets/DatasheetPanel-Cf4tI-nV.css","./assets/InfluenceLineView-Bj5RnXJC.js","./assets/ModelDoctor-B_s-eftz.css","./assets/ModelDoctor-LQSMJKHJ.js","./assets/Phase2DxfAction-B-G4nsw7.js","./assets/Phase2DxfAction-CTC8C-Q0.css","./assets/Phase2ProjectHub-B901vQ7m.js","./assets/Phase2ProjectHub-B9uSPOzx.css","./assets/PortableImportCenter-Cn1GDuG3.js","./assets/PwaUpdateNotice-4n5B8gfU.js","./assets/PwaUpdateNotice-Bl8tvzjR.css","./assets/Space3DWorkspace-C63BzSaN.css","./assets/Space3DWorkspace-tMjYyrmL.js","./assets/StructureGeneratorSurface-CrzECfAw.js","./assets/WorkspaceShell-BSxhSlFt.css","./assets/WorkspaceShell-QjEeHTJH.js","./assets/analysis.worker-DGXEcNhh.js","./assets/arrow-left-84YSX5c3.js","./assets/browser-DEYugRT4.js","./assets/bulkEditPresentation-BdnSfBby.js","./assets/check-TtOjy2VR.js","./assets/chevron-down-DvC6-qr7.js","./assets/chevron-up-CI86NwUe.js","./assets/controls-BG7Z7vwC.js","./assets/copy-DYQ6Hb5S.js","./assets/createLucideIcon-Cml3-wEV.js","./assets/defaultProject-BTVa8YJY.js","./assets/editor-PMuT98QN.js","./assets/es-CEbGEA7n.js","./assets/index-CSndF0J1.css","./assets/index-CsUwpgL6.js","./assets/influence.worker-BSqlB4fk.js","./assets/jsx-runtime-CaR_m4Xc.js","./assets/lightbulb-CQFTF1n2.js","./assets/math-B9PrbyNy.js","./assets/migrate-2QiLPlC2.js","./assets/modelDoctorDiagnostics-C03hlVbm.js","./assets/motionFeatures-DQVvClFS.js","./assets/pDelta-DrbjpcTH.js","./assets/pdf-CSNEjSHA.js","./assets/pdf.worker-Dg_VPFYK.mjs","./assets/pdf.worker-HAhvYgAe.js","./assets/portable-C98-FSy2.js","./assets/portableExportAnalysis-CdLwDxU5.js","./assets/portableFile-DSzlLRNk.js","./assets/projectCommand-BPHIQ_MT.js","./assets/projectRepository-KlHAdA_I.js","./assets/reliability-BCrQkPo9.js","./assets/rolldown-runtime-CNC7AqOf.js","./assets/rotate-ccw-Buo9FQbH.js","./assets/scenarios.worker-BT5F1kqK.js","./assets/search-BsKZzysk.js","./assets/shield-check-BzmKnplT.js","./assets/space3d.worker-BPyTSpGZ.js","./assets/structuralEditing-BXCbFJ-i.js","./assets/structureGeneration-C2BrNAGx.js","./assets/structureGenerator-BCkNzaMh.css","./assets/structureGenerator-BsaO9Tq7.js","./assets/structureGeometry-Bd9TH8n8.js","./assets/toolRegistry-8UYKbzRX.js","./assets/triangle-alert-D_MQgJqe.js","./assets/undo-2-DSILmKkL.js","./assets/usePhase2I18n-JU-2EtCC.js","./assets/weight-CXVkDAZb.js","./assets/workerHandlers-CU272dTi.js","./assets/workspaceCommands-DQp7zB9J.js","./assets/wrench-BqGoelox.js","./favicon.svg","./fonts/ibm-plex-mono-400.woff2","./fonts/ibm-plex-mono-500.woff2","./fonts/ibm-plex-sans-400.woff2","./fonts/ibm-plex-sans-500.woff2","./fonts/ibm-plex-sans-600.woff2","./fonts/ibm-plex-sans-700.woff2","./icons.svg","./index.html","./site.webmanifest"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(SHELL))));
self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.method!=='GET'||new URL(request.url).origin!==self.location.origin)return;
  if(request.mode==='navigate'){
    event.respondWith(fetch(request).then(response=>{
      if(response.ok)event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',response.clone())));
      return response;
    }).catch(async()=>await caches.match('./index.html',{ignoreVary:true})||await caches.match('./',{ignoreVary:true})));
    return;
  }
  event.respondWith(caches.match(request,{ignoreVary:true}).then(cached=>cached||fetch(request).then(response=>{
    if(response.ok)event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.put(request,response.clone())));
    return response;
  })));
});